name = "alcanciapp-api"
main = "src/index.js"
compatibility_date = "2024-02-20"
keep_vars = true

[vars]
CORS_ORIGIN = "*"
EMAIL_PROVIDER = "resend"
EMAIL_FROM = "AlcanciApp <login@intaprd.com>"
FROM_EMAIL = "AlcanciApp <login@intaprd.com>"

[[d1_databases]]
binding = "DB"
database_name = "alcanciapp-d1"
database_id = "6f897661-718f-4b8a-9a62-c5ba951db869"
